### ISSUE TITLE
Make card elements stylable

### ISSUE THREAD

**Issue by kdw2060** [thomasloven/lovelace-more-info-card#1]
Hi,

i've noticed I can't use card-mod to style the text on this card. Is there a workaround or would you consider making this possible?

thanks for having a look,
Kris

**Comment by thomasloven** [comment]
That's news to me...
![image](https://user-images.githubusercontent.com/1299821/71982627-343fda00-3225-11ea-8a23-9e2f32b61b63.png)

**Comment by kdw2060** [comment]
More specifically it's a Waze travel time sensor and I'm trying to style the key/value pairs using their class attribute.

**Comment by thomasloven** [comment]
Also definitely doable
![image](https://user-images.githubusercontent.com/1299821/71994860-c520b080-3239-11ea-99e0-a91fd3cf8469.png)
