### ISSUE TITLE
More Info has changed for 0.115.x

### ISSUE THREAD

**Issue by jimz011** [thomasloven/lovelace-more-info-card#10]
It seems the more-info window has changed in 0.115.x. It will render the card still, however it will only show a on/off button. All other stuff that used to be in the more-info-card window (like colorwheel or history and such) is no longer working.

Just thought I'd let you know since we are on b9 and haven't seen anyone mentioning it before. (maybe you don't even use this card yourself).

Thanks for your hard work,

Jimz011

**Comment by thib5** [comment]
I Noticed the Same Thing 

Thanks

**Comment by JamieP83** [comment]
same, doesnt work for me either

Home Assistant 0.115.6


arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 5.2
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.5
supervisor | 245
timezone | Europe/London
version | 0.115.6
virtualenv | false

**Comment by thib5** [comment]
Do you think you will be able de fix it ? or I should think about redoing my UI with other thing ?

**Comment by clemalex824** [comment]
The same... 😢
Since 0.115 this card doesn't work..
