### ISSUE TITLE
No more info since HA Update to 115

### ISSUE THREAD

**Issue by Jurgenn22** [thomasloven/lovelace-more-info-card#11]
@thomasloven 
More info is no longer visible since HA Update to 115.

Regards

**Comment by JAAlperin** [comment]
Yes.  I very much miss it.  Clicking the card does nothing.

**Comment by woodmj74** [comment]
Wasn't working for me, but since moving to 0.118 it seems to have come alive again!! :-)

**Comment by JAAlperin** [comment]
Yup.  Working again for me also.

Regards,

Jeff Alperin

H: 561-666-7789
C: 561-797-9876
