### ISSUE TITLE
Attributes hidden after HA update to 2021.6.x

### ISSUE THREAD

**Issue by nepozs** [thomasloven/lovelace-more-info-card#17]
Before HA update card had sensible look
![more-info-card_old](https://user-images.githubusercontent.com/56661567/121582223-0a4ca180-ca2f-11eb-86d4-7ce70231c8d8.jpg)

but now it looks like:
![more-info-card_new_Screenshot 2021-06-10 at 21-02-32 Przegląd - Home Assistant png](https://user-images.githubusercontent.com/56661567/121582608-80510880-ca2f-11eb-98b3-655722a8bf64.jpg)

and needs manual excpand (so using card makes no sense):
![more-info-card_new_expanded_Screenshot 2021-06-10 at 21-02-32 Przegląd - Home Assistant png](https://user-images.githubusercontent.com/56661567/121582679-98288c80-ca2f-11eb-8eac-72b880560060.jpg)

**Comment by GLehnhoff** [comment]
Same with me.
See pics below.

Problem:
With the HA update, attributes are not shown anymore by default and even worse, I can't change/manipulate the language of the word "Attributes" (see pics below). 

Possible solution:
I am kindly asking for the possibility to (a) change language of the word "Attributes", or (b) the chance to select by myself, whether I display the old or the new style. In addition to that, (c) it would be worthfull if the footer can also be in my language or that I get the possibility to not show the footer at all.

Thanks, gl

![grafik](https://user-images.githubusercontent.com/5453201/121666113-3442aa00-caa9-11eb-96e2-f6c399908619.png)
![grafik](https://user-images.githubusercontent.com/5453201/121666213-49b7d400-caa9-11eb-85d8-529a5f754b8a.png)

**Comment by nepozs** [comment]
@GLehnhoff 
Instead more-info-card I've used entity-attributes-card where applicable (e.g. a hard disk SMART attribute list, but may also be useful in your configuration):
https://github.com/custom-cards/entity-attributes-card
it can look like this
![attributes-card-Screenshot 2021-06-16 at 01-49-05 Poziomo - Home Assistant](https://user-images.githubusercontent.com/56661567/122137607-52136480-ce45-11eb-896a-081bce679716.png)

**Comment by bcutter** [comment]
Yap. HA Core 2021.6 made this card pretty useless for some/many/maybe most use-cases when it comes to listing text information unfortunately. It´s still useful for graphical things like light entities details (brightness, color etc.).

Thx @nepozs for bringing up entity-attributes-card which works pretty fine so far.

Maybe more-info-card can somehow access the attributes section and hopefully provide a configuration default like "always closed / always opened".

**Comment by thomasloven** [comment]
This is due to upstream changes in Home Assistant.

**Comment by nepozs** [comment]
Thanks for the answer, but is it understood that adding an option like "always opened" (like mentioned by @bcutter) is impossible?
