### ISSUE TITLE
History bars not appearing for vacuum entity

### ISSUE THREAD

**Issue by Alfiegerner** [thomasloven/lovelace-more-info-card#7]
Hi,

Thanks very much for this card, finding it very useful.  Small issue that history bars aren't being rendered for a vacuum entity.

Here is the standard more info:

![image](https://user-images.githubusercontent.com/596188/90087028-e6b5bd80-dd6f-11ea-894a-a9331a5dded4.png)

and this is the result if I use the card:

![image](https://user-images.githubusercontent.com/596188/90087700-86278000-dd71-11ea-886d-dafaa1e94c6b.png)

Here's the lovelace syntax I'm using:

```
entity: vacuum.chop_chop
title: ' '
type: 'custom:more-info-card'
```

Thanks.

**Comment by thomasloven** [comment]
Unfortunately, I had to remove the history graph component in 0.113.
I'm looking at ways to add it back.

**Comment by Alfiegerner** [comment]
Thanks.

**Comment by spudje** [comment]
Why is this closed? History bars are not back yet, are they?
